### ISSUE TITLE
Documentation Tracker

### ISSUE THREAD

**Issue by samuelfangjw** [StrawHats12/CS3219_strawhats#87]
**Due on Wednesday, 10 Nov 2021, 1700**

- Background and process 
    - [x] @kormingsoon 
- Requirements
    - [x]  @minzzelo 
- Development Docs
    - [x] Development Process @rtshkmr 
    - [x] Architecture and DevOps @samuelfangjw 
    - [x] Listings and Accounts @samuelfangjw 
    - [x] Messaging @minzzelo 
    - [x] Livestream @rtshkmr 
    - [x] Bidding @kormingsoon 
    - [x] Frontend @samuelfangjw (do last)
- Future Improvements
    - [x] @kormingsoon (All to contributions)
- Reflections and Learning Points
    - [x] @rtshkmr 
    - [x] @kormingsoon 
    - [x] @minzzelo 
    - [x] @samuelfangjw

**Comment by rtshkmr** [comment]
Completed!
